### ISSUE TITLE
scrape data from APIs with controllers

### ISSUE THREAD

**Issue by huangyvonnee** [Magana/roadtripr#16]

**Comment by Magana** [comment]
Closed with a9e37220735e6526d76633e5bb65e840f381687e, 6c5dca9e687edb97c65bc9457ca4c67e0cbf49c0, aa74a462f4e86b3d4fc255e67290cb5238dbf723

**Comment by Magana** [comment]
Closed with a9e37220735e6526d76633e5bb65e840f381687e, 6c5dca9e687edb97c65bc9457ca4c67e0cbf49c0, aa74a462f4e86b3d4fc255e67290cb5238dbf723
