### ISSUE TITLE
Filter Button

### ISSUE THREAD

**Issue by ruchi-shekar** [Magana/roadtripr#53]
When clicking or deleting a filter, the user has to click the filter button to make it actually filter. It'd be great if the filters happened automatically instead of after clicking the button, since it's more intuitive and convenient for the user.

**Comment by AmruthaSreedharane** [comment]
![filterissue](https://user-images.githubusercontent.com/14795011/38637606-3c4f094e-3d91-11e8-8e4a-a09b9e63ddd3.gif)
