### ISSUE TITLE
Instance Page Picture

### ISSUE THREAD

**Issue by ruchi-shekar** [Magana/roadtripr#56]
The picture for the instance is really large on your instance pages, it'd be more clean to look at if the picture was smaller.

**Comment by AmruthaSreedharane** [comment]
![image](https://user-images.githubusercontent.com/14795011/38636917-3fab5388-3d8f-11e8-9c04-c865c61af442.png)

**Comment by Magana** [comment]
closed in b84b6ab4a2bfe08a5c1cb354edd9cd5aaa84f121
