### ISSUE TITLE
'No Results Found' message

### ISSUE THREAD

**Issue by ruchi-shekar** [Magana/roadtripr#60]
We'd love to see a 'No Results Found' message when filtering/sorting returns no data on Parks and Cities.

**Comment by AmruthaSreedharane** [comment]
<img width="1280" alt="screen shot 2018-04-11 at 2 18 50 pm" src="https://user-images.githubusercontent.com/14795011/38638244-51d422f2-3d93-11e8-93ca-1ec605f6d226.png">
