### ISSUE TITLE
More Spacing between Filters

### ISSUE THREAD

**Issue by ruchi-shekar** [Magana/roadtripr#61]
It'd be nice if there was more spacing between filters. 
Ex: State Filter is right against the 'Min Pop.' label on Cities

**Comment by AmruthaSreedharane** [comment]
<img width="504" alt="screen shot 2018-04-11 at 2 17 26 pm" src="https://user-images.githubusercontent.com/14795011/38638193-20b069e2-3d93-11e8-9dd1-c54b503df9a3.png">

**Comment by Magana** [comment]
Closed in 2cc042e9c8cd2add76a45c7c587d84035f270afb
